# Generated by Django 5.1.7 on 2025-04-10 17:30

import django_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django_auth.models.BlangoUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
