# Generated by Django 5.1.7 on 2025-03-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='objects_id',
            new_name='object_id',
        ),
    ]
